### ISSUE TITLE
dataset read

### ISSUE THREAD

**Issue by snehashis1997** [zugexiaodui/campus_vad_code#1]
how to extract 7z files and is there any python or ubuntu command?

**Comment by zugexiaodui** [comment]
Please refer to this answer. https://askubuntu.com/questions/341628/how-to-extract-tar-7z-files-from-command-line

**Comment by snehashis1997** [comment]
thanks

**Comment by suvra97** [comment]
Hello @snehashis1997 . Were you able to extract the .7z files? Currently I am getting "Can not open the file as [7z] archive" error. Any help would be greatly appreciated.
