### ISSUE TITLE
The supplementary materials and complete code

### ISSUE THREAD

**Issue by JacksJ111** [zugexiaodui/campus_vad_code#10]
It's a great study !
Let me ask you a few questions.
When will the complete code be published? I would like to know how you preprocess the dataset and how you train and test it.I can not find the supplementary materials
Thank you very much!

**Comment by zugexiaodui** [comment]
Most of the codes have been released and some of the bidirectional prediction codes is being organized. I can send you the experimental codes of this part by email if you eagerly need them. The supplementary material is available at: https://openaccess.thecvf.com/content/CVPR2023/html/Cao_A_New_Comprehensive_Benchmark_for_Semi-Supervised_Video_Anomaly_Detection_and_CVPR_2023_paper.html

**Comment by JacksJ111** [comment]
Thanks! I can wait for a while and wish you a happy new year in advance.

**Comment by wyclike** [comment]
What a great work!Could u send me your experomental codes? I have greate interest in this work and hope to follow it .
My email is : 528813339@qq.com

**Comment by JacksJ111** [comment]
> Most of the codes have been released and some of the bidirectional prediction codes is being organized. I can send you the experimental codes of this part by email if you eagerly need them. The supplementary material is available at: https://openaccess.thecvf.com/content/CVPR2023/html/Cao_A_New_Comprehensive_Benchmark_for_Semi-Supervised_Video_Anomaly_Detection_and_CVPR_2023_paper.html

Excuse me，Could u send me the complete code? I  hope to follow it .Thank you！
My email is : jlw599848462@163.com

**Comment by Reynoll** [comment]
> Most of the codes have been released and some of the bidirectional prediction codes is being organized. I can send you the experimental codes of this part by email if you eagerly need them. The supplementary material is available at: https://openaccess.thecvf.com/content/CVPR2023/html/Cao_A_New_Comprehensive_Benchmark_for_Semi-Supervised_Video_Anomaly_Detection_and_CVPR_2023_paper.html

I need it too. Could u please send me the experimental codes?
My email is: 208024903@qq.com

**Comment by zugexiaodui** [comment]
Sent.

**Comment by wangsssky** [comment]
I need it too. Could u please send me the experimental codes?
My email is: [1245707261@qq.com](mailto:1245707261@qq.com)

**Comment by yinyexingchen** [comment]
> Sent.

I need it too. Could u please send me the experimental codes?
My email is: 1613627210@qq.com

**Comment by yinyexingchen** [comment]
> Most of the codes have been released and some of the bidirectional prediction codes is being organized. I can send you the experimental codes of this part by email if you eagerly need them. The supplementary material is available at: https://openaccess.thecvf.com/content/CVPR2023/html/Cao_A_New_Comprehensive_Benchmark_for_Semi-Supervised_Video_Anomaly_Detection_and_CVPR_2023_paper.html

Hello author,I am also interested in the TPAMI extension of your work.Could you please share the code.My email is: 1613627210@qq.com

**Comment by zugexiaodui** [comment]
> > Most of the codes have been released and some of the bidirectional prediction codes is being organized. I can send you the experimental codes of this part by email if you eagerly need them. The supplementary material is available at: https://openaccess.thecvf.com/content/CVPR2023/html/Cao_A_New_Comprehensive_Benchmark_for_Semi-Supervised_Video_Anomaly_Detection_and_CVPR_2023_paper.html
> 
> Hello author,I am also interested in the TPAMI extension of your work.Could you please share the code.My email is: [1613627210@qq.com](mailto:1613627210@qq.com)

Please contact Hanwen Zhang ([zhwwww@mail.nwpu.edu.cn](mailto:zhwwww@mail.nwpu.edu.cn)) for the detailed information and code of the extended version of our paper published in TPAMI. We sincerely appreciate your interest in our work.

**Comment by yinyexingchen** [comment]
> > > Most of the codes have been released and some of the bidirectional prediction codes is being organized. I can send you the experimental codes of this part by email if you eagerly need them. The supplementary material is available at: https://openaccess.thecvf.com/content/CVPR2023/html/Cao_A_New_Comprehensive_Benchmark_for_Semi-Supervised_Video_Anomaly_Detection_and_CVPR_2023_paper.html
> > 
> > 
> > Hello author,I am also interested in the TPAMI extension of your work.Could you please share the code.My email is: [1613627210@qq.com](mailto:1613627210@qq.com)
> 
> Please contact Hanwen Zhang ([zhwwww@mail.nwpu.edu.cn](mailto:zhwwww@mail.nwpu.edu.cn)) for the detailed information and code of the extended version of our paper published in TPAMI. We sincerely appreciate your interest in our work.

Hello, I have already contacted Hanwen   Zhang. He is currently on an internship，so it's not very nice to disturb him. So could you please offer me some help and share the source code to me?

**Comment by Tonyeeeee** [comment]
> Most of the codes have been released and some of the bidirectional prediction codes is being organized. I can send you the experimental codes of this part by email if you eagerly need them. The supplementary material is available at: https://openaccess.thecvf.com/content/CVPR2023/html/Cao_A_New_Comprehensive_Benchmark_for_Semi-Supervised_Video_Anomaly_Detection_and_CVPR_2023_paper.html

Hi, thank you for the code release! Could you share the experimental code? I would like to reproduce the results. Thanks!
My email is : [r13922a10@csie.ntu.edu.tw](mailto:r13922a10@csie.ntu.edu.tw)

**Comment by zugexiaodui** [comment]
@Tonyeeeee I have uploaded the code to Google Drive: https://drive.google.com/file/d/1X0q-KNM7z8urLJlwcMPfvE59YzK_y9IH/view?usp=drive_link
