### ISSUE TITLE
Video data processing

### ISSUE THREAD

**Issue by Zxy92999** [zugexiaodui/campus_vad_code#12]
dear author，Let me ask you a few questions.
how to deal raw video data，including video files, frame files, and track information.
I know，tracking files can download from link you provided。
but i dont know how deal videos_dir ，leave only files with the same name as the track file?
and i dont know how to get the frame files  which code i can use？or i need deal by myself？
If you can, can you give me your contact information? My email：68793839@qq.com I appreciate your quick response.pls

**Comment by zugexiaodui** [comment]
Dealing raw video data is a cumbersome stuff since different datasets have different formats.
I have send an email to you.

**Comment by Zxy92999** [comment]
I have already dealt with it, but I found that the memory usage during the training process is too high. Is there a way to solve it?

**Comment by zugexiaodui** [comment]
You may try "workers=2" to reduce the memory usage.

**Comment by monstercatz** [comment]
dear author，I am studying your article, but I have encountered some problems in data processing. Could you share the code of data processing with me if it is convenient. my email: 2296345660@qq.com

**Comment by zugexiaodui** [comment]
> dear author，I am studying your article, but I have encountered some problems in data processing. Could you share the code of data processing with me if it is convenient. my email: [2296345660@qq.com](mailto:2296345660@qq.com)

Hi! The codes of data processing have been included in `main/dsets.py`. Please check this file for more detailes.​

**Comment by yinyexingchen** [comment]
> dear author，Let me ask you a few questions. how to deal raw video data，including video files, frame files, and track information. I know，tracking files can download from link you provided。 but i dont know how deal videos_dir ，leave only files with the same name as the track file? and i dont know how to get the frame files which code i can use？or i need deal by myself？ If you can, can you give me your contact information? My email：[68793839@qq.com](mailto:68793839@qq.com) I appreciate your quick response.pls

hello, I would like to ask if the video dir can be omitted because the test set of the Shanghai dataset does not have videos. And if the scene information needs to be extracted, how should it be placed? Thanks in advance!

**Comment by zugexiaodui** [comment]
The video_dir cannot be omitted since it is used for checking frames during initilization of Dataset. You may modify the codes to ommit it. The scene information does not need to be extracted manually.
