### ISSUE TITLE
Corrupt .7z Files.

### ISSUE THREAD

**Issue by suvra97** [zugexiaodui/campus_vad_code#2]
Great work! I wanted to ask if you could re-upload the dataset for Google Drive. The downloaded .7z files are currently giving an "Can not open the file as [7z] archive" error. Please let me know if i'm making a stupid mistake in this. Any help would be appreciated. Thank You.

**Comment by zugexiaodui** [comment]
@suvra97 Sorry for the late reply. I'm trying to download the dataset and I will re-upload if any files are corrupted. Please wait for my reply. :D

**Comment by suvra97** [comment]
Thank You for your response. The corrupt file was on my end. The issue has been solved. Thank you again.
