### ISSUE TITLE
请问mmcv版本是什么呀

### ISSUE THREAD

**Issue by lidajing07** [zugexiaodui/campus_vad_code#3]
下载不下来mmcv

**Comment by zugexiaodui** [comment]
The version of mmcv is 1.6.2. However, you may use a newer version of mmcv since the codes only use some simple APIs.

**Comment by lidajing07** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lidajing07** [comment]
Thank you！
