### ISSUE TITLE
Query regarding input

### ISSUE THREAD

**Issue by suvra97** [zugexiaodui/campus_vad_code#5]
Thank you for your work. I am having some trouble understanding the inputs to the 1-train_sce.sh file. In the arguments what is the track_dir. What directory is it referring to. Looking at the other files, it seems to me that some object tracking features have been used. If that is so, could you please share what algorithm has been used, as I couldn't find any mentioned in the paper. 

Please correct me if I am wrong and excuse if I've overlooked some crucial detail in the paper. Thank you in advance for any help.

**Comment by zugexiaodui** [comment]
Sorry I forgot to upload the tracking file. I will upload the files as soon as possible.

**Comment by zugexiaodui** [comment]
链接：https://pan.baidu.com/s/1aPVPLlVq3FZEYzhy20qNiQ 
提取码：uq3i
