### ISSUE TITLE
Problem with downloading Tracking data file

### ISSUE THREAD

**Issue by Saini-Praveen** [zugexiaodui/campus_vad_code#7]
Thank you for your work. I am having issue with downloading the tracking file shared in baidu. Will it be possible for the google drive link for the same to be provided. It would be a great help for those who don't have access to baidu.

Thank You in advance.

**Comment by zugexiaodui** [comment]
Thank you for your suggestion. The tracking file has been uploaded to Google Drive: https://drive.google.com/file/d/1d-UaJT4Vfr3ke4AFkDA_pi7gMXo05ymS/view
